AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: fantasy forecaster service

Resources:
  FantasyForecasterModel:
    Type: 'AWS::Serverless::Function'
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: model/
      DockerTag: latest
    Properties:
      FunctionName: FantasyForecasterModel
      PackageType: Image
      ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/fantasy-forecaster:latest"
      MemorySize: 1536
      Timeout: 120
      Environment:
        Variables:
          DB_READ: "prod"
          DB_WRITE: "prod"
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt FantasyForecasterTable.Arn
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: !Sub "arn:aws:s3:::fantasy-forecaster-data/*"
      Events:
        # FETCH PLAYERS
        FetchPlayersFootballMorning:
          Type: 'Schedule'
          Properties:
            Schedule: 'cron(0 12 ? * 3-7 *)'  # 6 AM CST (12 PM UTC)
            Input: '{"action": "fetchPlayers", "sport": "football-2025", "league": "purdue"}'
        FetchPlayersFootballAfternoon:
          Type: 'Schedule'
          Properties:
            Schedule: 'cron(0 22 ? * 3-7 *)'  # 4 PM CST (10 PM UTC)
            Input: '{"action": "fetchPlayers", "sport": "football-2025", "league": "purdue"}'

        # FETCH LEAGUE
        PurdueFetchLeagueMorning:
          Type: 'Schedule'
          Properties:
            Schedule: 'cron(10 12 ? * 3-7 *)'  # 6:10 AM CST (12:10 PM UTC)
            Input: '{"action": "fetchLeague", "sport": "football-2025", "league": "purdue"}'
        PurdueFetchLeagueAfternoon:
          Type: 'Schedule'
          Properties:
            Schedule: 'cron(10 22 ? * 3-7 *)'  # 4:10 PM CST (10:10 PM UTC)
            Input: '{"action": "fetchLeague", "sport": "football-2025", "league": "purdue"}'
        WhaleWatchersFetchLeague:
          Type: 'Schedule'
          Properties:
            Schedule: 'cron(20 12 ? * 3-7 *)'  # 6:20 AM CST (12:20 PM UTC)
            Input: '{"action": "fetchLeague", "sport": "football-2025", "league": "whalewatchers"}'

        # RUN SIM
        PurdueSim1:
          Type: 'Schedule'
          Properties:
            Schedule: 'cron(30 12 ? * 3-7 *)' # 6:30 AM CST (12:30 PM UTC)
            Input: '{"action": "sim", "sport": "football-2025", "league": "purdue"}'
        PurdueSim2:
          Type: 'Schedule'
          Properties:
            Schedule: 'cron(30 22 ? * 3-7 *)' # 4:30 PM CST (10:30 PM UTC)
            Input: '{"action": "sim", "sport": "football-2025", "league": "purdue"}'
        WhaleWatchersSim:
          Type: 'Schedule'
          Properties:
            Schedule: 'cron(40 12 ? * 3-7 *)' # 6:40 AM CST (12:40 PM UTC)
            Input: '{"action": "sim", "sport": "football-2025", "league": "whalewatchers"}'

  FantasyForecasterApi:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: FantasyForecasterApi
      Handler: handler.lambda_handler
      Runtime: python3.13
      MemorySize: 256
      Timeout: 5
      CodeUri: api/
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !GetAtt FantasyForecasterTable.Arn
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /fantasy-forecaster/data
            Method: GET

  FantasyForecasterTable:
    Type: 'AWS::Serverless::SimpleTable'
    Properties:
      TableName: FantasyForecasterTable
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  ApiGatewayUrl:
    Description: "URL of the API Gateway"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fantasy-forecaster/data"
