AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: fantasy forecaster service

Resources:
  FantasyForecasterModel:
    Type: 'AWS::Serverless::Function'
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: model/
      DockerTag: latest
    Properties:
      PackageType: Image
      ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/fantasy-forecaster:latest"
      MemorySize: 1024
      Timeout: 120
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt FantasyForecasterTable.Arn
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: !Sub "arn:aws:s3:::fantasy-forecast-data/*"
      Events:
        ScheduledEvent:
          Type: 'Schedule'
          Properties:
            Schedule: 'rate(30 minutes)'  # Adjust the schedule as needed
            Input: '{}'

  FantasyForecasterTable:
    Type: 'AWS::Serverless::SimpleTable'
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
