
normal_weights = {
    0: {
        'projection': 0,
        'moving_projection': 0,
        'season_total': 0,
        'season_avg': 0,
        'moving_avg': 0,
        'sharp_moving_avg': 0,
        'expected_rostered': 20,
        'preseason_total': 40,
        'preseason_avg': 40,
    },
    1: {
        'projection': 15,
        'moving_projection': 0,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 0,
        'sharp_moving_avg': 0,
        'expected_rostered': 20,
        'preseason_total': 30,
        'preseason_avg': 30,
    },
    2: {
        'projection': 20,
        'moving_projection': 0,
        'season_total': 0,
        'season_avg': 10,
        'moving_avg': 0,
        'sharp_moving_avg': 0,
        'expected_rostered': 20,
        'preseason_total': 25,
        'preseason_avg': 25,
    },
    3: {
        'projection': 25,
        'moving_projection': 5,
        'season_total': 0,
        'season_avg': 10,
        'moving_avg': 0,
        'sharp_moving_avg': 0,
        'expected_rostered': 20,
        'preseason_total': 20,
        'preseason_avg': 20,
    },
    4: {
        'projection': 25,
        'moving_projection': 10,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 10,
        'sharp_moving_avg': 0,
        'expected_rostered': 20,
        'preseason_total': 15,
        'preseason_avg': 15,
    },
    5: {
        'projection': 27,
        'moving_projection': 16,
        'season_total': 2,
        'season_avg': 5,
        'moving_avg': 10,
        'sharp_moving_avg': 0,
        'expected_rostered': 20,
        'preseason_total': 10,
        'preseason_avg': 10,
    },
    6: {
        'projection': 30,
        'moving_projection': 20,
        'season_total': 3,
        'season_avg': 5,
        'moving_avg': 10,
        'sharp_moving_avg': 0,
        'expected_rostered': 20,
        'preseason_total': 5,
        'preseason_avg': 6,
    },
    7: {
        'projection': 30,
        'moving_projection': 20,
        'season_total': 4,
        'season_avg': 6,
        'moving_avg': 10,
        'sharp_moving_avg': 0,
        'expected_rostered': 20,
        'preseason_total': 0,
        'preseason_avg': 10,
    },
    8: {
        'projection': 30,
        'moving_projection': 20,
        'season_total': 4,
        'season_avg': 6,
        'moving_avg': 10,
        'sharp_moving_avg': 0,
        'expected_rostered': 20,
        'preseason_total': 0,
        'preseason_avg': 10,
    },
    9: {
        'projection': 31,
        'moving_projection': 21,
        'season_total': 4,
        'season_avg': 6,
        'moving_avg': 10,
        'sharp_moving_avg': 0,
        'expected_rostered': 20,
        'preseason_total': 0,
        'preseason_avg': 8,
    },
    10: {
        'projection': 32,
        'moving_projection': 22,
        'season_total': 4,
        'season_avg': 6,
        'moving_avg': 10,
        'sharp_moving_avg': 0,
        'expected_rostered': 20,
        'preseason_total': 0,
        'preseason_avg': 6,
    },
    11: {
        'projection': 33,
        'moving_projection': 23,
        'season_total': 4,
        'season_avg': 6,
        'moving_avg': 10,
        'sharp_moving_avg': 0,
        'expected_rostered': 20,
        'preseason_total': 0,
        'preseason_avg': 4,
    },
    12: {
        'projection': 34,
        'moving_projection': 24,
        'season_total': 4,
        'season_avg': 6,
        'moving_avg': 10,
        'sharp_moving_avg': 0,
        'expected_rostered': 20,
        'preseason_total': 0,
        'preseason_avg': 2,
    },
    13: {
        'projection': 34,
        'moving_projection': 24,
        'season_total': 4,
        'season_avg': 6,
        'moving_avg': 10,
        'sharp_moving_avg': 0,
        'expected_rostered': 20,
        'preseason_total': 0,
        'preseason_avg': 2,
    },
    14: {
        'projection': 34,
        'moving_projection': 24,
        'season_total': 4,
        'season_avg': 6,
        'moving_avg': 10,
        'sharp_moving_avg': 0,
        'expected_rostered': 20,
        'preseason_total': 0,
        'preseason_avg': 2,
    },
    15: {
        'projection': 34,
        'moving_projection': 24,
        'season_total': 4,
        'season_avg': 6,
        'moving_avg': 10,
        'sharp_moving_avg': 0,
        'expected_rostered': 20,
        'preseason_total': 0,
        'preseason_avg': 2,
    },
    16: {
        'projection': 34,
        'moving_projection': 24,
        'season_total': 4,
        'season_avg': 6,
        'moving_avg': 10,
        'sharp_moving_avg': 0,
        'expected_rostered': 20,
        'preseason_total': 0,
        'preseason_avg': 2,
    },
    17: {
        'projection': 34,
        'moving_projection': 24,
        'season_total': 4,
        'season_avg': 6,
        'moving_avg': 10,
        'sharp_moving_avg': 0,
        'expected_rostered': 20,
        'preseason_total': 0,
        'preseason_avg': 2,
    },
    18: {
        'avg_projection': 15,
        'total_projection': 35,
        'season_total': 35,
        'season_avg': 15,
    },
}


short_term_weights = {
    0: {
        'projection': 0,
        'moving_projection': 0,
        'season_total': 0,
        'season_avg': 0,
        'moving_avg': 0,
        'sharp_moving_avg': 0,
        'expected_rostered': 30,
        'preseason_total': 30,
        'preseason_avg': 40,
    },
    1: {
        'projection': 30,
        'moving_projection': 0,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 0,
        'sharp_moving_avg': 0,
        'expected_rostered': 15,
        'preseason_total': 25,
        'preseason_avg': 25,
    },
    2: {
        'projection': 35,
        'moving_projection': 0,
        'season_total': 0,
        'season_avg': 10,
        'moving_avg': 0,
        'sharp_moving_avg': 0,
        'expected_rostered': 15,
        'preseason_total': 20,
        'preseason_avg': 20,
    },
    3: {
        'projection': 40,
        'moving_projection': 5,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 0,
        'sharp_moving_avg': 5,
        'expected_rostered': 15,
        'preseason_total': 15,
        'preseason_avg': 15,
    },
    4: {
        'projection': 45,
        'moving_projection': 10,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 0,
        'sharp_moving_avg': 10,
        'expected_rostered': 10,
        'preseason_total': 10,
        'preseason_avg': 10,
    },
    5: {
        'projection': 50,
        'moving_projection': 15,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 0,
        'sharp_moving_avg': 15,
        'expected_rostered': 5,
        'preseason_total': 5,
        'preseason_avg': 5,
    },
    6: {
        'projection': 55,
        'moving_projection': 15,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 0,
        'sharp_moving_avg': 15,
        'expected_rostered': 5,
        'preseason_total': 0,
        'preseason_avg': 5,
    },
    7: {
        'projection': 55,
        'moving_projection': 15,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 0,
        'sharp_moving_avg': 15,
        'expected_rostered': 5,
        'preseason_total': 0,
        'preseason_avg': 5,
    },
    8: {
        'projection': 55,
        'moving_projection': 15,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 0,
        'sharp_moving_avg': 15,
        'expected_rostered': 5,
        'preseason_total': 0,
        'preseason_avg': 5,
    },
    9: {
        'projection': 55,
        'moving_projection': 15,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 0,
        'sharp_moving_avg': 15,
        'expected_rostered': 5,
        'preseason_total': 0,
        'preseason_avg': 5,
    },
    10: {
        'projection': 58,
        'moving_projection': 15,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 0,
        'sharp_moving_avg': 15,
        'expected_rostered': 5,
        'preseason_total': 0,
        'preseason_avg': 2,
    },
    11: {
        'projection': 58,
        'moving_projection': 15,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 0,
        'sharp_moving_avg': 15,
        'expected_rostered': 5,
        'preseason_total': 0,
        'preseason_avg': 2,
    },
    12: {
        'projection': 58,
        'moving_projection': 15,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 0,
        'sharp_moving_avg': 15,
        'expected_rostered': 5,
        'preseason_total': 0,
        'preseason_avg': 2,
    },
    13: {
        'projection': 59,
        'moving_projection': 16,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 0,
        'sharp_moving_avg': 15,
        'expected_rostered': 5,
        'preseason_total': 0,
        'preseason_avg': 0,
    },
    14: {
        'projection': 59,
        'moving_projection': 16,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 0,
        'sharp_moving_avg': 15,
        'expected_rostered': 5,
        'preseason_total': 0,
        'preseason_avg': 0,
    },
    15: {
        'projection': 59,
        'moving_projection': 16,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 0,
        'sharp_moving_avg': 15,
        'expected_rostered': 5,
        'preseason_total': 0,
        'preseason_avg': 0,
    },
    16: {
        'projection': 59,
        'moving_projection': 16,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 0,
        'sharp_moving_avg': 15,
        'expected_rostered': 5,
        'preseason_total': 0,
        'preseason_avg': 0,
    },
    17: {
        'projection': 59,
        'moving_projection': 16,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 0,
        'sharp_moving_avg': 15,
        'expected_rostered': 5,
        'preseason_total': 0,
        'preseason_avg': 0,
    },
    18: {
        'projection': 59,
        'moving_projection': 16,
        'season_total': 0,
        'season_avg': 5,
        'moving_avg': 0,
        'sharp_moving_avg': 15,
        'expected_rostered': 5,
        'preseason_total': 0,
        'preseason_avg': 0,
    },
}

